### ISSUE TITLE
Questions about the code about the criterion.py

### ISSUE THREAD

**Issue by syy-whu** [facebookresearch/3detr#31]
Hello, I do not understand the code "assign = linear_sum_assignment(final_cost[b, :, : nactual_gt[b]])", especially the nactual_gt. why not "assign = linear_sum_assignment(final_cost[b, :, : ])" ? Thanks for your great work and hope your reply soon!

**Comment by ch3cook-fdu** [comment]
the original implementation includes nactual_gt[b] objects to be matched, the rest are set as background. However, your implementation includes background objects that are initialized as [0, 0, 0, ...], which makes no sense.

**Comment by imisra** [comment]
Hi @syy-whu 

The cost matrix `final_cost[b,:,:nactual_gt[b]]` is the assignment cost matrix between the predicted proposals and the actual number of ground truth boxes (nactual_gt[b]). Since the number of ground truth objects can be different per scene in the batch, we select only the `nactual_gt[b]` objects.

**Comment by syy-whu** [comment]
Thanks for your sincere reply and your great work!

Ishan Misra ***@***.***> 于2022年3月11日周五 02:22写道：
